# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GenerateRS.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("GenerateRS.proto", :syntax => :proto3) do
    add_message "RemoteDeviceInfo" do
      optional :rq_size, :uint32, 1
      optional :rq_data, :bytes, 2
      optional :rq_sig_size, :uint32, 3
      optional :rq_sig_data, :bytes, 4
      optional :grappa_session_id, :uint32, 5
      optional :key_fair_play_guid_length, :uint32, 6
      optional :key_fair_play_guid, :bytes, 7
      optional :fair_play_certificate_length, :uint32, 8
      optional :fair_play_certificate, :bytes, 9
      optional :fair_device_type, :int64, 10
      optional :private_key, :uint32, 11
      optional :fair_play_guid_len, :uint32, 12
      optional :fair_play_guid, :string, 13
    end
    add_message "rsdata" do
      optional :rs_size, :uint32, 1
      optional :rs_data, :bytes, 2
    end
  end
end

RemoteDeviceInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RemoteDeviceInfo").msgclass
Rsdata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rsdata").msgclass
