# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GenerateRS.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("GenerateRS.proto", :syntax => :proto3) do
    add_message "AppleRemoteAuth.RemoteDeviceInfo" do
      optional :rq_data, :bytes, 1
      optional :rq_sig_data, :bytes, 2
      optional :grappa_session_id, :uint32, 3
      optional :key_fair_play_guid, :bytes, 4
      optional :fair_play_certificate, :bytes, 5
      optional :fair_device_type, :int64, 6
      optional :private_key, :uint32, 7
      optional :fair_play_guid, :string, 8
      proto3_optional :grappa, :bytes, 9
    end
    add_message "AppleRemoteAuth.rsdata" do
      optional :rs_data, :bytes, 1
      optional :ret, :bool, 2
      proto3_optional :rs_sig_data, :bytes, 3
    end
  end
end

module AppleRemoteAuth
  RemoteDeviceInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AppleRemoteAuth.RemoteDeviceInfo").msgclass
  Rsdata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AppleRemoteAuth.rsdata").msgclass
end
