// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GenerateRS.proto

package AppleRemoteAuth;

public final class GenerateRS {
  private GenerateRS() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RemoteDeviceInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AppleRemoteAuth.RemoteDeviceInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes rq_data = 1;</code>
     * @return The rqData.
     */
    com.google.protobuf.ByteString getRqData();

    /**
     * <code>bytes rq_sig_data = 2;</code>
     * @return The rqSigData.
     */
    com.google.protobuf.ByteString getRqSigData();

    /**
     * <code>uint32 grappa_session_id = 3;</code>
     * @return The grappaSessionId.
     */
    int getGrappaSessionId();

    /**
     * <code>bytes key_fair_play_guid = 4;</code>
     * @return The keyFairPlayGuid.
     */
    com.google.protobuf.ByteString getKeyFairPlayGuid();

    /**
     * <code>bytes fair_play_certificate = 5;</code>
     * @return The fairPlayCertificate.
     */
    com.google.protobuf.ByteString getFairPlayCertificate();

    /**
     * <code>int64 fair_device_type = 6;</code>
     * @return The fairDeviceType.
     */
    long getFairDeviceType();

    /**
     * <code>uint32 private_key = 7;</code>
     * @return The privateKey.
     */
    int getPrivateKey();

    /**
     * <code>string fair_play_guid = 8;</code>
     * @return The fairPlayGuid.
     */
    java.lang.String getFairPlayGuid();
    /**
     * <code>string fair_play_guid = 8;</code>
     * @return The bytes for fairPlayGuid.
     */
    com.google.protobuf.ByteString
        getFairPlayGuidBytes();
  }
  /**
   * <pre>
   * The request message 
   * </pre>
   *
   * Protobuf type {@code AppleRemoteAuth.RemoteDeviceInfo}
   */
  public static final class RemoteDeviceInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AppleRemoteAuth.RemoteDeviceInfo)
      RemoteDeviceInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RemoteDeviceInfo.newBuilder() to construct.
    private RemoteDeviceInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RemoteDeviceInfo() {
      rqData_ = com.google.protobuf.ByteString.EMPTY;
      rqSigData_ = com.google.protobuf.ByteString.EMPTY;
      keyFairPlayGuid_ = com.google.protobuf.ByteString.EMPTY;
      fairPlayCertificate_ = com.google.protobuf.ByteString.EMPTY;
      fairPlayGuid_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RemoteDeviceInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RemoteDeviceInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              rqData_ = input.readBytes();
              break;
            }
            case 18: {

              rqSigData_ = input.readBytes();
              break;
            }
            case 24: {

              grappaSessionId_ = input.readUInt32();
              break;
            }
            case 34: {

              keyFairPlayGuid_ = input.readBytes();
              break;
            }
            case 42: {

              fairPlayCertificate_ = input.readBytes();
              break;
            }
            case 48: {

              fairDeviceType_ = input.readInt64();
              break;
            }
            case 56: {

              privateKey_ = input.readUInt32();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              fairPlayGuid_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AppleRemoteAuth.GenerateRS.internal_static_AppleRemoteAuth_RemoteDeviceInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AppleRemoteAuth.GenerateRS.internal_static_AppleRemoteAuth_RemoteDeviceInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AppleRemoteAuth.GenerateRS.RemoteDeviceInfo.class, AppleRemoteAuth.GenerateRS.RemoteDeviceInfo.Builder.class);
    }

    public static final int RQ_DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString rqData_;
    /**
     * <code>bytes rq_data = 1;</code>
     * @return The rqData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRqData() {
      return rqData_;
    }

    public static final int RQ_SIG_DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString rqSigData_;
    /**
     * <code>bytes rq_sig_data = 2;</code>
     * @return The rqSigData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRqSigData() {
      return rqSigData_;
    }

    public static final int GRAPPA_SESSION_ID_FIELD_NUMBER = 3;
    private int grappaSessionId_;
    /**
     * <code>uint32 grappa_session_id = 3;</code>
     * @return The grappaSessionId.
     */
    @java.lang.Override
    public int getGrappaSessionId() {
      return grappaSessionId_;
    }

    public static final int KEY_FAIR_PLAY_GUID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString keyFairPlayGuid_;
    /**
     * <code>bytes key_fair_play_guid = 4;</code>
     * @return The keyFairPlayGuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getKeyFairPlayGuid() {
      return keyFairPlayGuid_;
    }

    public static final int FAIR_PLAY_CERTIFICATE_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString fairPlayCertificate_;
    /**
     * <code>bytes fair_play_certificate = 5;</code>
     * @return The fairPlayCertificate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getFairPlayCertificate() {
      return fairPlayCertificate_;
    }

    public static final int FAIR_DEVICE_TYPE_FIELD_NUMBER = 6;
    private long fairDeviceType_;
    /**
     * <code>int64 fair_device_type = 6;</code>
     * @return The fairDeviceType.
     */
    @java.lang.Override
    public long getFairDeviceType() {
      return fairDeviceType_;
    }

    public static final int PRIVATE_KEY_FIELD_NUMBER = 7;
    private int privateKey_;
    /**
     * <code>uint32 private_key = 7;</code>
     * @return The privateKey.
     */
    @java.lang.Override
    public int getPrivateKey() {
      return privateKey_;
    }

    public static final int FAIR_PLAY_GUID_FIELD_NUMBER = 8;
    private volatile java.lang.Object fairPlayGuid_;
    /**
     * <code>string fair_play_guid = 8;</code>
     * @return The fairPlayGuid.
     */
    @java.lang.Override
    public java.lang.String getFairPlayGuid() {
      java.lang.Object ref = fairPlayGuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fairPlayGuid_ = s;
        return s;
      }
    }
    /**
     * <code>string fair_play_guid = 8;</code>
     * @return The bytes for fairPlayGuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFairPlayGuidBytes() {
      java.lang.Object ref = fairPlayGuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fairPlayGuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!rqData_.isEmpty()) {
        output.writeBytes(1, rqData_);
      }
      if (!rqSigData_.isEmpty()) {
        output.writeBytes(2, rqSigData_);
      }
      if (grappaSessionId_ != 0) {
        output.writeUInt32(3, grappaSessionId_);
      }
      if (!keyFairPlayGuid_.isEmpty()) {
        output.writeBytes(4, keyFairPlayGuid_);
      }
      if (!fairPlayCertificate_.isEmpty()) {
        output.writeBytes(5, fairPlayCertificate_);
      }
      if (fairDeviceType_ != 0L) {
        output.writeInt64(6, fairDeviceType_);
      }
      if (privateKey_ != 0) {
        output.writeUInt32(7, privateKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fairPlayGuid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, fairPlayGuid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!rqData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, rqData_);
      }
      if (!rqSigData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, rqSigData_);
      }
      if (grappaSessionId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, grappaSessionId_);
      }
      if (!keyFairPlayGuid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, keyFairPlayGuid_);
      }
      if (!fairPlayCertificate_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, fairPlayCertificate_);
      }
      if (fairDeviceType_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, fairDeviceType_);
      }
      if (privateKey_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, privateKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fairPlayGuid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, fairPlayGuid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AppleRemoteAuth.GenerateRS.RemoteDeviceInfo)) {
        return super.equals(obj);
      }
      AppleRemoteAuth.GenerateRS.RemoteDeviceInfo other = (AppleRemoteAuth.GenerateRS.RemoteDeviceInfo) obj;

      if (!getRqData()
          .equals(other.getRqData())) return false;
      if (!getRqSigData()
          .equals(other.getRqSigData())) return false;
      if (getGrappaSessionId()
          != other.getGrappaSessionId()) return false;
      if (!getKeyFairPlayGuid()
          .equals(other.getKeyFairPlayGuid())) return false;
      if (!getFairPlayCertificate()
          .equals(other.getFairPlayCertificate())) return false;
      if (getFairDeviceType()
          != other.getFairDeviceType()) return false;
      if (getPrivateKey()
          != other.getPrivateKey()) return false;
      if (!getFairPlayGuid()
          .equals(other.getFairPlayGuid())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RQ_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getRqData().hashCode();
      hash = (37 * hash) + RQ_SIG_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getRqSigData().hashCode();
      hash = (37 * hash) + GRAPPA_SESSION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getGrappaSessionId();
      hash = (37 * hash) + KEY_FAIR_PLAY_GUID_FIELD_NUMBER;
      hash = (53 * hash) + getKeyFairPlayGuid().hashCode();
      hash = (37 * hash) + FAIR_PLAY_CERTIFICATE_FIELD_NUMBER;
      hash = (53 * hash) + getFairPlayCertificate().hashCode();
      hash = (37 * hash) + FAIR_DEVICE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFairDeviceType());
      hash = (37 * hash) + PRIVATE_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPrivateKey();
      hash = (37 * hash) + FAIR_PLAY_GUID_FIELD_NUMBER;
      hash = (53 * hash) + getFairPlayGuid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AppleRemoteAuth.GenerateRS.RemoteDeviceInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AppleRemoteAuth.GenerateRS.RemoteDeviceInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AppleRemoteAuth.GenerateRS.RemoteDeviceInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AppleRemoteAuth.GenerateRS.RemoteDeviceInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AppleRemoteAuth.GenerateRS.RemoteDeviceInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AppleRemoteAuth.GenerateRS.RemoteDeviceInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AppleRemoteAuth.GenerateRS.RemoteDeviceInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AppleRemoteAuth.GenerateRS.RemoteDeviceInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AppleRemoteAuth.GenerateRS.RemoteDeviceInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AppleRemoteAuth.GenerateRS.RemoteDeviceInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AppleRemoteAuth.GenerateRS.RemoteDeviceInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AppleRemoteAuth.GenerateRS.RemoteDeviceInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AppleRemoteAuth.GenerateRS.RemoteDeviceInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The request message 
     * </pre>
     *
     * Protobuf type {@code AppleRemoteAuth.RemoteDeviceInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AppleRemoteAuth.RemoteDeviceInfo)
        AppleRemoteAuth.GenerateRS.RemoteDeviceInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AppleRemoteAuth.GenerateRS.internal_static_AppleRemoteAuth_RemoteDeviceInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AppleRemoteAuth.GenerateRS.internal_static_AppleRemoteAuth_RemoteDeviceInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AppleRemoteAuth.GenerateRS.RemoteDeviceInfo.class, AppleRemoteAuth.GenerateRS.RemoteDeviceInfo.Builder.class);
      }

      // Construct using AppleRemoteAuth.GenerateRS.RemoteDeviceInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rqData_ = com.google.protobuf.ByteString.EMPTY;

        rqSigData_ = com.google.protobuf.ByteString.EMPTY;

        grappaSessionId_ = 0;

        keyFairPlayGuid_ = com.google.protobuf.ByteString.EMPTY;

        fairPlayCertificate_ = com.google.protobuf.ByteString.EMPTY;

        fairDeviceType_ = 0L;

        privateKey_ = 0;

        fairPlayGuid_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AppleRemoteAuth.GenerateRS.internal_static_AppleRemoteAuth_RemoteDeviceInfo_descriptor;
      }

      @java.lang.Override
      public AppleRemoteAuth.GenerateRS.RemoteDeviceInfo getDefaultInstanceForType() {
        return AppleRemoteAuth.GenerateRS.RemoteDeviceInfo.getDefaultInstance();
      }

      @java.lang.Override
      public AppleRemoteAuth.GenerateRS.RemoteDeviceInfo build() {
        AppleRemoteAuth.GenerateRS.RemoteDeviceInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public AppleRemoteAuth.GenerateRS.RemoteDeviceInfo buildPartial() {
        AppleRemoteAuth.GenerateRS.RemoteDeviceInfo result = new AppleRemoteAuth.GenerateRS.RemoteDeviceInfo(this);
        result.rqData_ = rqData_;
        result.rqSigData_ = rqSigData_;
        result.grappaSessionId_ = grappaSessionId_;
        result.keyFairPlayGuid_ = keyFairPlayGuid_;
        result.fairPlayCertificate_ = fairPlayCertificate_;
        result.fairDeviceType_ = fairDeviceType_;
        result.privateKey_ = privateKey_;
        result.fairPlayGuid_ = fairPlayGuid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AppleRemoteAuth.GenerateRS.RemoteDeviceInfo) {
          return mergeFrom((AppleRemoteAuth.GenerateRS.RemoteDeviceInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AppleRemoteAuth.GenerateRS.RemoteDeviceInfo other) {
        if (other == AppleRemoteAuth.GenerateRS.RemoteDeviceInfo.getDefaultInstance()) return this;
        if (other.getRqData() != com.google.protobuf.ByteString.EMPTY) {
          setRqData(other.getRqData());
        }
        if (other.getRqSigData() != com.google.protobuf.ByteString.EMPTY) {
          setRqSigData(other.getRqSigData());
        }
        if (other.getGrappaSessionId() != 0) {
          setGrappaSessionId(other.getGrappaSessionId());
        }
        if (other.getKeyFairPlayGuid() != com.google.protobuf.ByteString.EMPTY) {
          setKeyFairPlayGuid(other.getKeyFairPlayGuid());
        }
        if (other.getFairPlayCertificate() != com.google.protobuf.ByteString.EMPTY) {
          setFairPlayCertificate(other.getFairPlayCertificate());
        }
        if (other.getFairDeviceType() != 0L) {
          setFairDeviceType(other.getFairDeviceType());
        }
        if (other.getPrivateKey() != 0) {
          setPrivateKey(other.getPrivateKey());
        }
        if (!other.getFairPlayGuid().isEmpty()) {
          fairPlayGuid_ = other.fairPlayGuid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AppleRemoteAuth.GenerateRS.RemoteDeviceInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AppleRemoteAuth.GenerateRS.RemoteDeviceInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString rqData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes rq_data = 1;</code>
       * @return The rqData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRqData() {
        return rqData_;
      }
      /**
       * <code>bytes rq_data = 1;</code>
       * @param value The rqData to set.
       * @return This builder for chaining.
       */
      public Builder setRqData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rqData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes rq_data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRqData() {
        
        rqData_ = getDefaultInstance().getRqData();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString rqSigData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes rq_sig_data = 2;</code>
       * @return The rqSigData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRqSigData() {
        return rqSigData_;
      }
      /**
       * <code>bytes rq_sig_data = 2;</code>
       * @param value The rqSigData to set.
       * @return This builder for chaining.
       */
      public Builder setRqSigData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rqSigData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes rq_sig_data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRqSigData() {
        
        rqSigData_ = getDefaultInstance().getRqSigData();
        onChanged();
        return this;
      }

      private int grappaSessionId_ ;
      /**
       * <code>uint32 grappa_session_id = 3;</code>
       * @return The grappaSessionId.
       */
      @java.lang.Override
      public int getGrappaSessionId() {
        return grappaSessionId_;
      }
      /**
       * <code>uint32 grappa_session_id = 3;</code>
       * @param value The grappaSessionId to set.
       * @return This builder for chaining.
       */
      public Builder setGrappaSessionId(int value) {
        
        grappaSessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 grappa_session_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGrappaSessionId() {
        
        grappaSessionId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString keyFairPlayGuid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes key_fair_play_guid = 4;</code>
       * @return The keyFairPlayGuid.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getKeyFairPlayGuid() {
        return keyFairPlayGuid_;
      }
      /**
       * <code>bytes key_fair_play_guid = 4;</code>
       * @param value The keyFairPlayGuid to set.
       * @return This builder for chaining.
       */
      public Builder setKeyFairPlayGuid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        keyFairPlayGuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes key_fair_play_guid = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeyFairPlayGuid() {
        
        keyFairPlayGuid_ = getDefaultInstance().getKeyFairPlayGuid();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString fairPlayCertificate_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes fair_play_certificate = 5;</code>
       * @return The fairPlayCertificate.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getFairPlayCertificate() {
        return fairPlayCertificate_;
      }
      /**
       * <code>bytes fair_play_certificate = 5;</code>
       * @param value The fairPlayCertificate to set.
       * @return This builder for chaining.
       */
      public Builder setFairPlayCertificate(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fairPlayCertificate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes fair_play_certificate = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearFairPlayCertificate() {
        
        fairPlayCertificate_ = getDefaultInstance().getFairPlayCertificate();
        onChanged();
        return this;
      }

      private long fairDeviceType_ ;
      /**
       * <code>int64 fair_device_type = 6;</code>
       * @return The fairDeviceType.
       */
      @java.lang.Override
      public long getFairDeviceType() {
        return fairDeviceType_;
      }
      /**
       * <code>int64 fair_device_type = 6;</code>
       * @param value The fairDeviceType to set.
       * @return This builder for chaining.
       */
      public Builder setFairDeviceType(long value) {
        
        fairDeviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 fair_device_type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearFairDeviceType() {
        
        fairDeviceType_ = 0L;
        onChanged();
        return this;
      }

      private int privateKey_ ;
      /**
       * <code>uint32 private_key = 7;</code>
       * @return The privateKey.
       */
      @java.lang.Override
      public int getPrivateKey() {
        return privateKey_;
      }
      /**
       * <code>uint32 private_key = 7;</code>
       * @param value The privateKey to set.
       * @return This builder for chaining.
       */
      public Builder setPrivateKey(int value) {
        
        privateKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 private_key = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrivateKey() {
        
        privateKey_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fairPlayGuid_ = "";
      /**
       * <code>string fair_play_guid = 8;</code>
       * @return The fairPlayGuid.
       */
      public java.lang.String getFairPlayGuid() {
        java.lang.Object ref = fairPlayGuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fairPlayGuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fair_play_guid = 8;</code>
       * @return The bytes for fairPlayGuid.
       */
      public com.google.protobuf.ByteString
          getFairPlayGuidBytes() {
        java.lang.Object ref = fairPlayGuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fairPlayGuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fair_play_guid = 8;</code>
       * @param value The fairPlayGuid to set.
       * @return This builder for chaining.
       */
      public Builder setFairPlayGuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fairPlayGuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fair_play_guid = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearFairPlayGuid() {
        
        fairPlayGuid_ = getDefaultInstance().getFairPlayGuid();
        onChanged();
        return this;
      }
      /**
       * <code>string fair_play_guid = 8;</code>
       * @param value The bytes for fairPlayGuid to set.
       * @return This builder for chaining.
       */
      public Builder setFairPlayGuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fairPlayGuid_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AppleRemoteAuth.RemoteDeviceInfo)
    }

    // @@protoc_insertion_point(class_scope:AppleRemoteAuth.RemoteDeviceInfo)
    private static final AppleRemoteAuth.GenerateRS.RemoteDeviceInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AppleRemoteAuth.GenerateRS.RemoteDeviceInfo();
    }

    public static AppleRemoteAuth.GenerateRS.RemoteDeviceInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RemoteDeviceInfo>
        PARSER = new com.google.protobuf.AbstractParser<RemoteDeviceInfo>() {
      @java.lang.Override
      public RemoteDeviceInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RemoteDeviceInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RemoteDeviceInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RemoteDeviceInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public AppleRemoteAuth.GenerateRS.RemoteDeviceInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface rsdataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AppleRemoteAuth.rsdata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes rs_data = 1;</code>
     * @return The rsData.
     */
    com.google.protobuf.ByteString getRsData();
  }
  /**
   * <pre>
   * The response message 
   * </pre>
   *
   * Protobuf type {@code AppleRemoteAuth.rsdata}
   */
  public static final class rsdata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AppleRemoteAuth.rsdata)
      rsdataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use rsdata.newBuilder() to construct.
    private rsdata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private rsdata() {
      rsData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new rsdata();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private rsdata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              rsData_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AppleRemoteAuth.GenerateRS.internal_static_AppleRemoteAuth_rsdata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AppleRemoteAuth.GenerateRS.internal_static_AppleRemoteAuth_rsdata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AppleRemoteAuth.GenerateRS.rsdata.class, AppleRemoteAuth.GenerateRS.rsdata.Builder.class);
    }

    public static final int RS_DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString rsData_;
    /**
     * <code>bytes rs_data = 1;</code>
     * @return The rsData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRsData() {
      return rsData_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!rsData_.isEmpty()) {
        output.writeBytes(1, rsData_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!rsData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, rsData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AppleRemoteAuth.GenerateRS.rsdata)) {
        return super.equals(obj);
      }
      AppleRemoteAuth.GenerateRS.rsdata other = (AppleRemoteAuth.GenerateRS.rsdata) obj;

      if (!getRsData()
          .equals(other.getRsData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RS_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getRsData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AppleRemoteAuth.GenerateRS.rsdata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AppleRemoteAuth.GenerateRS.rsdata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AppleRemoteAuth.GenerateRS.rsdata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AppleRemoteAuth.GenerateRS.rsdata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AppleRemoteAuth.GenerateRS.rsdata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AppleRemoteAuth.GenerateRS.rsdata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AppleRemoteAuth.GenerateRS.rsdata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AppleRemoteAuth.GenerateRS.rsdata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AppleRemoteAuth.GenerateRS.rsdata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AppleRemoteAuth.GenerateRS.rsdata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AppleRemoteAuth.GenerateRS.rsdata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AppleRemoteAuth.GenerateRS.rsdata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AppleRemoteAuth.GenerateRS.rsdata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The response message 
     * </pre>
     *
     * Protobuf type {@code AppleRemoteAuth.rsdata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AppleRemoteAuth.rsdata)
        AppleRemoteAuth.GenerateRS.rsdataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AppleRemoteAuth.GenerateRS.internal_static_AppleRemoteAuth_rsdata_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AppleRemoteAuth.GenerateRS.internal_static_AppleRemoteAuth_rsdata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AppleRemoteAuth.GenerateRS.rsdata.class, AppleRemoteAuth.GenerateRS.rsdata.Builder.class);
      }

      // Construct using AppleRemoteAuth.GenerateRS.rsdata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rsData_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AppleRemoteAuth.GenerateRS.internal_static_AppleRemoteAuth_rsdata_descriptor;
      }

      @java.lang.Override
      public AppleRemoteAuth.GenerateRS.rsdata getDefaultInstanceForType() {
        return AppleRemoteAuth.GenerateRS.rsdata.getDefaultInstance();
      }

      @java.lang.Override
      public AppleRemoteAuth.GenerateRS.rsdata build() {
        AppleRemoteAuth.GenerateRS.rsdata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public AppleRemoteAuth.GenerateRS.rsdata buildPartial() {
        AppleRemoteAuth.GenerateRS.rsdata result = new AppleRemoteAuth.GenerateRS.rsdata(this);
        result.rsData_ = rsData_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AppleRemoteAuth.GenerateRS.rsdata) {
          return mergeFrom((AppleRemoteAuth.GenerateRS.rsdata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AppleRemoteAuth.GenerateRS.rsdata other) {
        if (other == AppleRemoteAuth.GenerateRS.rsdata.getDefaultInstance()) return this;
        if (other.getRsData() != com.google.protobuf.ByteString.EMPTY) {
          setRsData(other.getRsData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AppleRemoteAuth.GenerateRS.rsdata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AppleRemoteAuth.GenerateRS.rsdata) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString rsData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes rs_data = 1;</code>
       * @return The rsData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRsData() {
        return rsData_;
      }
      /**
       * <code>bytes rs_data = 1;</code>
       * @param value The rsData to set.
       * @return This builder for chaining.
       */
      public Builder setRsData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rsData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes rs_data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRsData() {
        
        rsData_ = getDefaultInstance().getRsData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AppleRemoteAuth.rsdata)
    }

    // @@protoc_insertion_point(class_scope:AppleRemoteAuth.rsdata)
    private static final AppleRemoteAuth.GenerateRS.rsdata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AppleRemoteAuth.GenerateRS.rsdata();
    }

    public static AppleRemoteAuth.GenerateRS.rsdata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<rsdata>
        PARSER = new com.google.protobuf.AbstractParser<rsdata>() {
      @java.lang.Override
      public rsdata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new rsdata(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<rsdata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<rsdata> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public AppleRemoteAuth.GenerateRS.rsdata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AppleRemoteAuth_RemoteDeviceInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AppleRemoteAuth_RemoteDeviceInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AppleRemoteAuth_rsdata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AppleRemoteAuth_rsdata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020GenerateRS.proto\022\017AppleRemoteAuth\"\325\001\n\020" +
      "RemoteDeviceInfo\022\017\n\007rq_data\030\001 \001(\014\022\023\n\013rq_" +
      "sig_data\030\002 \001(\014\022\031\n\021grappa_session_id\030\003 \001(" +
      "\r\022\032\n\022key_fair_play_guid\030\004 \001(\014\022\035\n\025fair_pl" +
      "ay_certificate\030\005 \001(\014\022\030\n\020fair_device_type" +
      "\030\006 \001(\003\022\023\n\013private_key\030\007 \001(\r\022\026\n\016fair_play" +
      "_guid\030\010 \001(\t\"\031\n\006rsdata\022\017\n\007rs_data\030\001 \001(\0142Q" +
      "\n\003aid\022J\n\nGenerateRS\022!.AppleRemoteAuth.Re" +
      "moteDeviceInfo\032\027.AppleRemoteAuth.rsdata\"" +
      "\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AppleRemoteAuth_RemoteDeviceInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AppleRemoteAuth_RemoteDeviceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AppleRemoteAuth_RemoteDeviceInfo_descriptor,
        new java.lang.String[] { "RqData", "RqSigData", "GrappaSessionId", "KeyFairPlayGuid", "FairPlayCertificate", "FairDeviceType", "PrivateKey", "FairPlayGuid", });
    internal_static_AppleRemoteAuth_rsdata_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AppleRemoteAuth_rsdata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AppleRemoteAuth_rsdata_descriptor,
        new java.lang.String[] { "RsData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
